name: CI-SABEMI-TEC
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: BUILD
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Restore
        run: dotnet restore SABEMI-TEC/SABEMI-TEC.sln
      - name: Build
        run: dotnet build SABEMI-TEC/SABEMI-TEC.sln --no-restore --configuration Release
        
  test:
    name: TESTES UNITÁRIOS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Restore
        run: dotnet restore SABEMI-TEC/SABEMI-TEC.sln
      - name: Test
        run: dotnet test SABEMI-TEC/SABEMI-TEC.sln --no-restore --configuration Release
        
  sonarqube:
    name: SONARQUBECLOUD
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: SonarQube Begin
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          dotnet sonarscanner begin
          /k:"fabianoCafu_SABEMI-TEC4"
          /o:"fabianocafu"
          /d:sonar.token="$SONAR_TOKEN"
          /d:sonar.host.url="https://sonarcloud.io"
          /d:sonar.sourceEncoding="UTF-8"
          /d:sonar.qualitygate.wait="true"
          /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml"

      - name: Restore
        run: dotnet restore SABEMI-TEC/SABEMI-TEC.sln

      - name: Build
        run: dotnet build SABEMI-TEC/SABEMI-TEC.sln --no-restore --configuration Release --no-incremental

      - name: Test
        run: >
          dotnet test SABEMI-TEC/SABEMI-TEC.sln
          --no-restore
          --configuration Release
          --no-build
          --collect:"XPlat Code Coverage"
          --DataCollectionSettings.DataCollectorInstance.Configuration.Format=opencover
            
      - name: SonarQube End
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"

  nuget:
    name: PUBLISH NUGET
    runs-on: ubuntu-latest
    needs: sonarqube

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Restore
        run: dotnet restore SABEMI-TEC/SABEMI-TEC.sln
      - name: Pack
        run: dotnet pack SABEMI-TEC/SABEMI-TEC.sln --no-restore --configuration Release
