name: CI-SABEMI-TEC

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:

  build-test-sonar:
    name: BUILD + TESTES + SONARQUBE
    runs-on: ubuntu-latest

    steps:

      # ==========================================
      # CHECKOUT
      # ==========================================
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ==========================================
      # .NET 6
      # ==========================================
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      # ==========================================
      # RESTORE
      # ==========================================
      - name: Restore
        run: dotnet restore SABEMI-TEC/SABEMI-TEC.sln

      # ==========================================
      # SONARSCANNER
      # ==========================================
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      # ==========================================
      # SONAR BEGIN
      # ==========================================
      - name: SonarQube Begin
        run: |
          dotnet sonarscanner begin \
            /k:"fabianoCafu_SABEMI-TEC4" \
            /o:"fabianocafu" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" \
            /d:sonar.qualitygate.wait=true

      # ==========================================
      # BUILD
      # ==========================================
      - name: Build
        run: |
          dotnet build SABEMI-TEC/SABEMI-TEC.sln \
            --no-restore \
            --configuration Release \
            --no-incremental

      # ==========================================
      # TESTES + COBERTURA
      # ==========================================
      - name: Test + Coverage
        run: |
          dotnet test SABEMI-TEC/SABEMI-TEC.sln \
            --configuration Release \
            --no-build \
            --no-restore \
            --collect:"XPlat Code Coverage" \
            --results-directory ./TestResults \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      # ==========================================
      # LOCALIZAR COBERTURA
      # ==========================================
      - name: List Coverage Files
        run: |
          echo "Arquivos de cobertura encontrados:"
          find . -name "coverage.opencover.xml" -type f

      # ==========================================
      # SONAR END
      # ==========================================
      - name: SonarQube End
        run: |
          dotnet sonarscanner end \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
